export const he = {
  schema: {
    creation: {
      defaultTitleSchema: "טופס ללא כותרת",
      defaultTitleSection: "סעיף ללא שם",
      defaultDescription: "תיאור טופס",
      defaultDescriptionSection: "תיאור (אופציונלי)",
      titlePlaceholder: "טופס ללא כותרת",
      descriptionPlaceholder: "תיאור טופס",
      addOption: "הוספת אפשרות",
      option: "אפשרות",
      rows: "שורות",
      cols: "עמודות",
      date: "יום, חודש, שנה",
      time: "זמן",
      optionalTag: "תווית (אופציונאלי)",
      shortText: "טקסט של תשובה קצרה",
      longText: "טקסט של תשובה ארוכה",
      baseQuestionDefaultText: "שאלה",
      saveButtonText: "שמור",
      publishSchemaButtonText: "פרסם",
      headerQuestionShortText: "תשובה קצרה",
      headerQuestionParagraph: "פסקה",
      headerQuestionRadio: "בחירה מרובה",
      headerQuestionCheckbox: "תיבות סימון",
      headerQuestionDropdown: "רשימה נפתחת",
      headerQuestionLinearScale: "סולם לינארי",
      headerQuestionRadioTable: "רשת של בחירה מרובה",
      headerQuestionCheckboxTable: "רשת תיבות סימון",
      headerQuestionDate: "תאריך",
      headerQuestionTime: "זמן",
      footerRequired: "נדרש",
      defaultValueOptionsState: "אפשרות 1",
    },
  },
  homePage: {
    creatingSchema: "יוצר..",
    createNewForm: "יצירת טופס",
    homeButton: "בית",
    editButton: "עריכה",
    deleteButton: "מחיקה",
    fillButton: "מילוי",
    viewButton: "צפייה",
    draftSchemas: "טפסים בעריכה",
    publishedSchemas: "טפסים למילוי",
    draftInstances: "מופעים בעריכה",
    publishedInstances: "מופעים שהגשתי",
  },
  instance: {
    creation: {
      loadingInstance: "טוען...",
      loadingError: "שגיאה בטעינת הטופס",
      defaultTextAnswer: "התשובה שלך",
      nextPage: "הבא",
      prevPage: "הקודם",
      submit: "הגשה",
      other: "אחר:",
      dropdownPlaceholder: "בחירה",
    },
  },
};
